In [28]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LinearRegression
import pandas as pd

In [7]:
df = pd.read_csv("Student_Marks.csv")

In [9]:
 df.head(3)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [10]:
y = df[["Marks"]] # Tahmin edeceğimiz şey
x = df[["number_courses","time_study"]] # Tahmin için gerekli olan değişkenler

In [12]:
df.info() # Data hakkında bilgi almak için

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [18]:
l = LinearRegression() # liner regresyonu başlatıyoruz
model = l.fit(x,y) # elimizdeki x'lerden y'yi bulması için eğitiyoruz

In [30]:
model.coef_ # Değikenlerin kat sayıları

array([[1.86405074, 5.39917879]])

In [31]:
model.intercept_ # Sabit yani y = ax + b denklemindeki b değeri

array([-7.45634623])

In [29]:
model.predict([[3,3]]) # Model girdilere göre tahmin yapıyor "number_courses","time_study"

array([[14.33334236]])

In [25]:
df["Marks"].max() # verisetindeki maksimum not değeri

np.float64(55.299)

In [26]:
model.score(x,y) # Model başarı değeri %94 ama %6'lık bir hata payı var

0.9403656320238896

In [32]:
 df.head(2)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734

In [41]:
s1 = model.predict([[3,4.508]])[0] # Mesela sıfırıncı indeksteki öğrencinin başarı notu 19.202 olmalı ama..

In [42]:
(19.202 - s1)/19.202 # bir sapma değerimiz var

array([-0.17046682])