In [12]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('Churn_Modelling.csv')

In [3]:
df=df.drop(columns=["RowNumber","CustomerId","Surname"])

In [4]:
df.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [5]:
df=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)

In [6]:
df.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1              False   
1               1        112542.58       0              False   
2               0        113931.57       1              False   

   Geography_Spain  Gender_Male  
0            False        False  
1             True        False  
2            False        False

In [7]:
y=df['Exited']
x=df.drop("Exited",axis=1)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=61,train_size=0.7)

In [9]:
rf=RandomForestClassifier()
model=rf.fit(x_train,y_train)

In [10]:
model.score(x_test,y_test)

0.8583333333333333

In [13]:
model.predict([[712,31,9,0,5,1,1,200000,False,False,True]])

array([1])

In [14]:
df=pd.DataFrame()

In [15]:
df['takim']=["BJK","BJK","FB","GS","XY","XT","AB","AC","TS","AG","ANT","MIY","DBS","AG","AG","RM","BAR","SS","BDR"]

In [16]:
pd.get_dummies(df,columns=["takim"])

takim_AB  takim_AC  takim_AG  takim_ANT  takim_BAR  takim_BDR  takim_BJK  \
0      False     False     False      False      False      False       True   
1      False     False     False      False      False      False       True   
2      False     False     False      False      False      False      False   
3      False     False     False      False      False      False      False   
4      False     False     False      False      False      False      False   
5      False     False     False      False      False      False      False   
6       True     False     False      False      False      False      False   
7      False      True     False      False      False      False      False   
8      False     False     False      False      False      False      False   
9      False     False      True      False      False      False      False   
10     False     False     False       True      False      False      False   
11     False     False     False      False      False      False      False   
12     False     False     False      False      False      False      False   
13     False     False      True      False      False      False      False   
14     False     False      True      False      False      False      False   
15     False     False     False      False      False      False      False   
16     False     False     False      False       True      False      False   
17     False     False     False      False      False      False      False   
18     False     False     False      False      False       True      False   

    takim_DBS  takim_FB  takim_GS  takim_MIY  takim_RM  takim_SS  takim_TS  \
0       False     False     False      False     False     False     False   
1       False     False     False      False     False     False     False   
2       False      True     False      False     False     False     False   
3       False     False      True      False     False     False     False   
4       False     False     False      False     False     False     False   
5       False     False     False      False     False     False     False   
6       False     False     False      False     False     False     False   
7       False     False     False      False     False     False     False   
8       False     False     False      False     False     False      True   
9       False     False     False      False     False     False     False   
10      False     False     False      False     False     False     False   
11      False     False     False       True     False     False     False   
12       True     False     False      False     False     False     False   
13      False     False     False      False     False     False     False   
14      False     False     False      False     False     False     False   
15      False     False     False      False      True     False     False   
16      False     False     False      False     False     False     False   
17      False     False     False      False     False      True     False   
18      False     False     False      False     False     False     False   

    takim_XT  takim_XY  
0      False     False  
1      False     False  
2      False     False  
3      False     False  
4      False      True  
5       True     False  
6      False     False  
7      False     False  
8      False     False  
9      False     False  
10     False     False  
11     False     False  
12     False     False  
13     False     False  
14     False     False  
15     False     False  
16     False     False  
17     False     False  
18     False     False

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
ohe=OneHotEncoder()

In [19]:
x=ohe.fit_transform(df[['takim']])

In [20]:
x.toarray()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,

In [21]:
ohe.transform([["FB"]]).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
df=pd.read_csv('Churn_Modelling.csv')
df=df.drop(columns=["RowNumber","CustomerId","Surname"])

In [23]:
df.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [24]:
ohe=OneHotEncoder()

In [25]:
xd=ohe.fit_transform(df[['Geography',"Gender"]]).toarray()

In [26]:
ohe.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [27]:
xd=pd.DataFrame(xd)

In [28]:
xd.columns=ohe.get_feature_names_out()

In [29]:
xd

Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                  1.0                0.0              0.0            1.0   
1                  0.0                0.0              1.0            1.0   
2                  1.0                0.0              0.0            1.0   
3                  1.0                0.0              0.0            1.0   
4                  0.0                0.0              1.0            1.0   
...                ...                ...              ...            ...   
9995               1.0                0.0              0.0            0.0   
9996               1.0                0.0              0.0            0.0   
9997               1.0                0.0              0.0            1.0   
9998               0.0                1.0              0.0            0.0   
9999               1.0                0.0              0.0            1.0   

      Gender_Male  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
9995          1.0  
9996          1.0  
9997          0.0  
9998          1.0  
9999          0.0  

[10000 rows x 5 columns]

In [30]:
df.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [31]:
df=df.drop(columns=["Geography","Gender"])

In [32]:
df.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1

In [33]:
df[xd.columns]=xd

In [34]:
df.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                0.0              0.0            1.0          0.0  
1                0.0              1.0            1.0          0.0  
2                0.0              0.0            1.0          0.0

In [35]:
y=df['Exited']
x=df.drop("Exited",axis=1)

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
tree=DecisionTreeClassifier()
model=tree.fit(x,y)
model.score(x,y)

# Overfiting Oldu :(

1.0

In [38]:
ohe.transform([["France","Female"]]).toarray()

array([[1., 0., 0., 1., 0.]])